openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Animals API
  description: Main Animals API
paths:
  /animals/{name}:
    get:
      description: Return animal by name
      parameters:
        - name: name
          in: query
          description: Name of the animal to retrieve
          required: true
          schema:
            type: string
      responses:
        default:
          description: Returns the matching animals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/pet"
components:
  schemas:
    pet:
      type: object
      required:
        - type
        - name
        - gender
        - weight
      properties:
        type:
          type: string
        name:
          type: string
        gender:
          type: string
        weight:
          type: integer
          format: int64